Latest DataBrowser works without this fix. Causing problems with using click module for generating cli scripts, so removing. Original issue was: AttributeError: 'module' object has no attribute 'argv' when using DB and conda venv.